//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18213
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Kinect.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Kinect.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter of type {0} not of of expected type {1} 的本地化字符串。
        /// </summary>
        internal static string DelegateCommandCastException {
            get {
                return ResourceManager.GetString("DelegateCommandCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All set! 的本地化字符串。
        /// </summary>
        internal static string MessageAllSet {
            get {
                return ResourceManager.GetString("MessageAllSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect is listening 的本地化字符串。
        /// </summary>
        internal static string MessageAllSetListening {
            get {
                return ResourceManager.GetString("MessageAllSetListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Kinect is being used by another application. 的本地化字符串。
        /// </summary>
        internal static string MessageConflict {
            get {
                return ResourceManager.GetString("MessageConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oops, there is an error. 的本地化字符串。
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        internal static string MessageInitializing {
            get {
                return ResourceManager.GetString("MessageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many USB devices! Please unplug one or more. 的本地化字符串。
        /// </summary>
        internal static string MessageInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MessageInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect required 的本地化字符串。
        /// </summary>
        internal static string MessageNoAvailableSensors {
            get {
                return ResourceManager.GetString("MessageNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This sensor is not genuine! 的本地化字符串。
        /// </summary>
        internal static string MessageNotGenuine {
            get {
                return ResourceManager.GetString("MessageNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plug my power cord in! 的本地化字符串。
        /// </summary>
        internal static string MessageNotPowered {
            get {
                return ResourceManager.GetString("MessageNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect for Xbox not supported. 的本地化字符串。
        /// </summary>
        internal static string MessageNotSupported {
            get {
                return ResourceManager.GetString("MessageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application needs a Kinect for Windows sensor in order to function. However, another application is using the Kinect Sensor. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationConflict {
            get {
                return ResourceManager.GetString("MoreInformationConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Kinect Sensor is plugged in, however an error has occurred. For steps to resolve, please click the &quot;Help&quot; link. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationError {
            get {
                return ResourceManager.GetString("MoreInformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Kinect Sensor needs the majority of the USB Bandwidth of a USB Controller. If other devices are in contention for that bandwidth, the Kinect Sensor may not be able to function. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MoreInformationInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationNoAvailableSensors {
            get {
                return ResourceManager.GetString("MoreInformationNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application needs a genuine Kinect for Windows sensor in order to function. Please plug one into the PC. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationNotGenuine {
            get {
                return ResourceManager.GetString("MoreInformationNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Kinect Sensor is plugged into the computer with its USB connection, but the power plug appears to be not powered. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationNotPowered {
            get {
                return ResourceManager.GetString("MoreInformationNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC. 的本地化字符串。
        /// </summary>
        internal static string MoreInformationNotSupported {
            get {
                return ResourceManager.GetString("MoreInformationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to launch the default web browser. Trying to navigate to: {0} 的本地化字符串。
        /// </summary>
        internal static string NoDefaultBrowserAvailable {
            get {
                return ResourceManager.GetString("NoDefaultBrowserAvailable", resourceCulture);
            }
        }
    }
}
